entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
api:
  dashboard: true
  insecure: false
certificatesResolvers:
  http:
    acme:
      email: you@example.com
      storage: acme.json
      httpChallenge:
        entryPoint: web
